src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use App\Entity\Booking;
use App\Entity\Comment;
use Cocur\Slugify\Slugify;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce possède déjà ce titre, merci de le modifier"
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères", maxMessage="Le titre ne peut pas faire plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description ne peut pas faire moins de 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function generateSlug() {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author): ?Comment {
        foreach ($this->comments as $comment) {
            if ($comment-> getAuthor() === $author) {
                return $comment;
            }
        }

        return null;
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @return float
     */
    public function getAvgRatings() {
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        return (count($this->comments) > 0) ? $sum / count($this->comments) : 0;
    }

    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation
     */
    public function getNotAvailableDays(): array
    {
        $notAvailableDays = [];

        /** @var Booking $booking*/
        foreach ($this->bookings as $booking) {
            // Calculer les jours qui se trouvent entre la date d'arrivée et de départ
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            $days = array_map(function($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ImageType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration('Titre', 'Titre de votre annonce'))
            ->add(
                'slug',
                TextType::class,
                $this->getConfiguration('Adresse web', 'Adresse web (automatique)', [
                    'required' => false
                ])
            )
            ->add('coverImage', UrlType::class, $this->getConfiguration('URL de l\'image', 'Donnez l\'adresse d\'une image qui donne vraiement envie'))
            ->add('introduction', TextType::class, $this->getConfiguration('Introduction', 'Donnez une description global de l\'annonce'))
            ->add('content', TextareaType::class, $this->getConfiguration('Description détaillé', 'Tapez une description qui donne vraiment envie de venir chez vous'))
            ->add('rooms', IntegerType::class, $this->getConfiguration('Nombre de chambres', 'Le nombre de chambres disponibles'))
            ->add('price', MoneyType::class, $this->getConfiguration('Prix par nuit', 'Indiquez le prix pour une nuit'))
            ->add(
                'images',
                CollectionType::class,
                [
                    'entry_type' => ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true,
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * Afficher tous les annonces
     *
     * @Route("/ads", name="app_ads_index")
     *
     * @return Response
     */
    public function index(AdRepository $adRepository): Response
    {
        $ads = $adRepository->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads,
        ]);
    }

    /**
     * Créer une annonce
     *
     * @Route("/ads/new", name="app_ads_new")
     *
     * @IsGranted("ROLE_USER")
     *
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        $ad = new Ad();

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $em->persist($image);
            }

            $ad->setAuthor($this->getUser());

            $em->persist($ad);
            $em->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée !"
            );

            return $this->redirectToRoute('app_ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Editer une annonce
     *
     * @Route("/ads/{slug}/edit", name="app_ads_edit")
     *
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas le modifier")
     *
     * @return Response
     */
    public function edit(Request $request, Ad $ad, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $em->persist($image);
            }

            $em->persist($ad);
            $em->flush();

            $this->addFlash(
                'success',
                "Les modifications de l'annonce <strong>{$ad->getTitle()}</strong> ont bien été enregistrée !"
            );

            return $this->redirectToRoute('app_ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Permet de supprimer une annonce
     *
     * @Route("/ads/{slug}/delete", name="app_ads_delete")
     *
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Vous n'avez pas le droit d'accéder à cette ressources")
     *
     * @param Ad $ad
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function delete(Ad $ad, EntityManagerInterface $em): Response
    {
        $em->remove($ad);
        $em->flush();

        $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été supprimée !"
        );

        return $this->redirectToRoute('app_ads_index');
    }

    /**
     * Afficher une seule annonce
     *
     * @Route("/ads/{slug}", name="app_ads_show")
     *
     * @return Response
     */
    public function show(Ad $ad): Response
    {    
        return $this->render('ad/show.html.twig', ['ad' => $ad]);
    }
}

templates/ad/_ad.html.twig
{% set url = path('app_ads_show', {'slug': ad.slug}) %}
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ad.price}}&euro; / nuit</strong><br>
            {% if ad.comments|length > 0 %}
                {% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}
        </div>
        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="image de {{ ad.title }}" style="height: 200px; width: 100%; display: block" />
        </a>
        <div class="card-body">
            <h4 class="card-title">
                <a href="{{ url }}">
                    {{ ad.title }}
                </a>
            </h4>
            <p class="card-text">{{ ad.introduction }}</p>
            <a class="btn btn-secondary" href="{{ url }}">En savoir plus</a>
            {% if app.user and app.user == ad.author %}
            <a href="{{ path('app_ads_edit', {'slug': ad.slug}) }}" class="btn btn-warning">Modifier l'annonce</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images !</p>

    {{ form_widget(form) }}

    <div class="form-group mb-4">
        <button type="button" class="btn btn-primary" id="add-image">Ajouter une image</button>
    </div>
{% endblock %}

{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
<div class="form-group mb-3" id="block_{{id}}">
    <div class="row">
        <div class="col-10">
            <div class="row">
                <div class="col">
                    {{ form_widget(form.url) }}
                    {{ form_errors(form.url) }}
                </div>
                <div class="col">
                    {{ form_widget(form.caption) }}
                    {{ form_errors(form.caption) }}
                </div>
            </div>
        </div>
        <div class="col-2">
            <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
        </div>
    </div>
</div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Edition d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
<div class="container">
    <h1>Modifier l'annonce {{ ad.title }}</h1>

    {{ form_start(form) }}

    {{ form_widget(form) }}

    <input type="hidden" id="widget-counter" value="0">

    <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>

    {{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('build/js/ad.js') }}"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}
<div class="container">
    <h1 class="my-3">Voici les annonces de nos hôtes!</h1>
    <div class="row">
        {% for ad in ads %}
            {% include "ad/_ad.html.twig" %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce{% endblock %}

{# appliquer le custom theme sur ce formulaire _self #}
{# {% form_theme form _self %} #}
{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
<div class="container">
    <h1>Créer une nouvelle annonce</h1>

    {{ form_start(form) }}

    {{ form_widget(form) }}

    <input type="hidden" id="widget-counter" value="0">

    <button type="submit" class="btn btn-primary">Créer la nouvelle annonce</button>

    {{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('build/js/ad.js') }}"></script>
{% endblock %}

{# custom theme #}
{# {% block form_row %}
<div class="form-group">
    {{ form_label(form) }}
    {{ form_widget(form) }}
</div>
{% endblock %}

{% block text_widget %}
    <input type="text" name="{{full_name}}" id="{{id}}" class="form-control">
{% endblock %} #}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ ad.title }}{% endblock %}

{% block body %}
<div class="ad-title" style="background-image: url({{ ad.coverImage }})">
    <div class="container">
        <h1>{{ ad.title }}</h1>
        <p>{{ ad.introduction }}</p>
        <p class="h2">
            <strong>{{ ad.rooms }} chambres</strong> pour <strong>{{ ad.price }}&euro;</strong> par nuit
        </p>
        <a href={{ path('app_booking_create', {'slug': ad.slug}) }} class="btn btn-primary">Réserver !</a>
        {% if app.user and app.user == ad.author %}
        <a href="{{ path('app_ads_edit', {'slug': ad.slug}) }}" class="btn btn-warning">Modifier l'annonce</a>
        <a href="{{ path('app_ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger" onclick="return confirm(`Êtes vous sur de vouloir supprimer l'annonce: {{ ad.title }}`)">Supprimer l'annonce</a>
        {% endif %}
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="alert alert-light">
                <h4 class="alert-heading">
                    <div class="row align-items-center">
                        <div class="col">
                            {% include "partials/rating.html.twig" with {'rating': ad.avgRatings} %}
                        </div>
                    </div>
                </h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 mb-3">
            {{ ad.content|raw }}
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
                <div class="carousel-indicators">
                {% for image in ad.images %}
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ loop.index0 }}" {% if loop.first %}class="active" aria-current="true" {% endif %} aria-label="Slide {{ loop.index }}"></button>
                {% endfor %}
                </div>
                <div class="carousel-inner">
                {% for image in ad.images %}
                    <div class="carousel-item {% if loop.first %}active{% endif %}">
                        <img src="{{ image.url }}" class="d-block w-100" alt="{{ image.caption }}">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>{{ ad.title }}</h5>
                            <p>{{ image.caption }}</p>
                        </div>
                    </div>
                {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
            <hr>
            {% if ad.comments|length > 0 %}
                <h2 class="mb-3">Commentaires de nos voyageurs</h2>
                {% for comment in ad.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3">
                        <strong>{{comment.author.firstname}}</strong> a dit:
                        <blockquote>
                            {{comment.content}}
                        </blockquote>
                        <strong>Note donnée: </strong><br>
                        {% include "partials/rating.html.twig" with {'rating': comment.rating} %}
                    </div>
                {% endfor %}
            {% else %}
                    <h2>Cette annonce n'a pas encore reçu de commentaires...</h2>
            {% endif %}
        </div>
        <div class="col">
            {% set author = ad.author %}
            <div class="row mb-3">
                <div class="col-3">
                    <a href="{{ path('app_user_index', { 'slug': author.slug }) }}">
                        <img src="{{ author.picture }}" class="avatar avatar-medium" alt="Avatar de {{ author.fullname }}">
                    </a>
                </div>
                <div class="col">
                    <a href="{{ path('app_user_index', { 'slug': author.slug }) }}">
                        <h3>{{ author.fullname }} </h3>
                    </a>
                    <span class="badge bg-primary">{{ author.ads | length }} annonces</span>
                </div>
            </div>
            {{ author.description | raw}}
        </div>
    </div>
</div>
{% endblock %}